ffbsee/ffbsee-webseite

- content/anleitung/flashen/contents.lr
- content/faq/contents.lr
fix multiple typos (related to #3 )
> fix typos #3

- content/anleitung/flashen/contents.lr
- content/anleitung/router/contents.lr
- content/anleitung/sicher-surfen/contents.lr
- content/anleitung/tftp/contents.lr
- content/anleitung/web/contents.lr
- content/contents.lr
- content/faq/contents.lr
Ich habe mir mal die Mühe gemacht und ein paar Seiten etwas genauer unter die Lupe genommen.
Da in der Zwischenzeit bereits ein paar Typos von @ynnk1 ausgebessert wurden, müsstet ihr nun manuell Mergen.
> fix various typos #3

- assets/.htaccess
++ rules for compression with mod_deflate.c
++ rules for cache with mod_expires. and mod_headers.c
+- rules for redirections with mod_rewrite.c changed
(!!! take care: we redirect www.ffbsee.net, freifunk-bodensee.net and www.freifunk-bodensee.net consequently to ffbsee.net)
> +- .htaccess changed:

- content/anleitung/web/contents.lr
IP von 192.169.133.1 auf  192.168.133.1 geändert.
Nicht wundern, beim Checkout war mein Git-Client noch nicht konfiguriert, deswegen steht da "ncadmin".
Jetzt schwitz ich aber!   :-)
> Fixed IP address in contents.tr to 192.168

- content/blog/finanzierung-der-freifunk-gateways/contents.lr
Kleiner Blogeintag zu der Thematik: Was gibt es für Server
> Status der Server bei FFBSee

- content/camp/camp18nachts.jpg
- content/camp/contents.lr
- content/camp/technikcamp2019.png
added pic of poster, added pic of last year, fixed some typos/spelling
> improved camp2019 site

- content/camp/contents.lr
> Add Unterkunft section to camp

- content/blog/eineliebe/antenne.jpg
- content/blog/eineliebe/antenne_natur.jpg
- content/blog/eineliebe/antenne_vom_zelt.jpg
- content/blog/eineliebe/antenne_vom_zelt_ohne_zelt.jpg
- content/blog/eineliebe/buehne.jpg
- content/blog/eineliebe/buehne_red.jpg
- content/blog/eineliebe/contents.lr
- content/blog/eineliebe/disko.jpg
- content/blog/eineliebe/eineliebe.jpg
- content/blog/eineliebe/kabelfuehrung.jpg
- content/blog/eineliebe/outdoow-switch.jpg
- content/blog/eineliebe/techn1k.jpg
- content/blog/eineliebe/technik.jpg
- content/blog/eineliebe/zelt_und_kabel.jpg
Wir waren dort und es gab Freifunk.
Also wird darüber auch berichtet!
> Blog Eintrag zum Eine Liebe Festival

- content/blog/firmware-2_0/contents.lr
> new Firmware

- Makefile
- configs/jsminify.ini
- ffbsee.net.lektorproject
sorry @maxbachmann, but i have to remove it (temporarily)
you can revert this pull request if you are resolve the issue
> JavaScript minify is creating trouble

- templates/layout.html
trying to add Link to freifunk karte to start menu point...first try, not sure this works - approve needed!
> add link to map under Start

- templates/layout.html
Reverts ffbsee/ffbsee-webseite#80
> Revert "add link to map under Start"

- content/anleitung/config/contents.lr
- content/anleitung/router/contents.lr
Korrektur einiger Anleitungstexte.
> Rechtschreibkorrektur

- content/anleitung/firmware-fuer-geraete-mit-wenig-flash-bauen/contents.lr
- content/anleitung/flashen/contents.lr
- content/anleitung/futro/contents.lr
- content/anleitung/matrix/contents.lr
- content/anleitung/mesh/contents.lr
- content/anleitung/recovery/contents.lr
- content/anleitung/router/contents.lr
- content/anleitung/tftp/contents.lr
- content/anleitung/treffen/contents.lr
- content/anleitung/web/contents.lr
- content/blog/eineliebe/contents.lr
- content/blog/eu-urheberrechtsreform-demo/contents.lr
- content/blog/firmware-2_0/contents.lr
Alle Anleitungen, ein bisschen Blog
> Rechtschreibkorrekturen

- ffbsee.net.lektorproject
added python2 support for everyone still using python2
fixes #87
> added python2 support

- databags/navigation.ini
- templates/layout.html
> use translated navigation titles

- content/anleitung/futro/contents.lr
+ Einige Korrekturen für das Futro flashen
+ Erweitern Flashen mit Kartenleser
+ vorzunehmende BIOS-Einstellungen
Vielleicht kommt man damit auch mit #86 etwas weiter...
> Get closer

- .github/FUNDING.yml
- Makefile
- assets/sass/layout/_header.scss
- content/helfen/contents.lr
- content/termine.ics/contents.lr
- templates/layout.html
This also includes some other drive-by changes:
- Move the arrow of the floating menu to the right
- Add calendar entry for the "Mitgliederversammlung" next week
> Update contribution page

- content/camp/camp17/contents.lr
- content/camp/camp18/contents.lr
- content/camp/camp19/contents.lr
- content/camp/contents.lr
- content/termine.ics/contents+en.lr
- content/termine.ics/contents.lr
- models/camppage.ini
- templates/camppage.html
- templates/layout.html
Vom 13-16. August 2020
Mit Terminkalnender und dem link nach ``ffbsee.net/camp``
> Technik Camp 2020

- content/anleitung/config/contents+en.lr
- content/anleitung/config/contents.lr
- content/anleitung/firmware-fuer-geraete-mit-wenig-flash-bauen/contents+en.lr
- content/anleitung/mesh/contents+en.lr
- content/anleitung/tftp/contents+en.lr
- content/anleitung/treffen/contents+en.lr
- content/anleitung/web/contents+en.lr
- content/blog/camp19/contents+en.lr
- content/blog/contents+en.lr
- content/blog/eineliebe/contents+en.lr
- content/blog/eineliebe/contents.lr
- content/blog/firmware-2_0/contents+en.lr
- content/blog/technik-camp-2019-recap/contents+en.lr
- content/camp/contents+en.lr
- content/datenschutz/contents+en.lr
- content/faq/contents+en.lr
Did "some" translation work (instructions, blog, Data Protection, ...)
> Translations

- assets/.htaccess
"media from src self" is e.g. the famous lisa-video on the homepage
> csp-headers allowing default and media-src 'self'

- databags/calendar.ini
- templates/start.html
this way the calendar is able to show an english translation (Issue #126 )
> ++ multi-language stuff for calendar
